### ISSUE TITLE
Release a new version at PyPi

### ISSUE THREAD

**Issue by dou-du** [Zulko/vapory#57]
The PyPi package seems broken. Local installation from the master branch is good. 
Could you release a new version at PyPi ? Thanks.

**Comment by yakutovicha** [comment]
I would support this request, as our tool depends on the vapory package ([see here](
https://github.com/aiidalab/aiidalab-widgets-base/blob/c5f8620a18ab3d1bb23031384ce506f1343ef392/setup.json#L27)). 

The issue is: when we try to install our package from PyPI, the things do not work, we get:

```python
Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
aiidalab-widgets-base depends on vapory@ git+https://github.com/Zulko/vapory.git@master
```

**Comment by Zulko** [comment]
Sorry for that! I have pushed the master to PyPI (v0.1.2) to hopefully unblock you.

**Comment by yakutovicha** [comment]
thanks, @Zulko, I think the issue can be closed.
